const express=require('express')
const usercontroller=require('../controllers/userController')
const midddlewares=require('../midddlewares/session')
const router = express.Router()

router.get('/login',midddlewares.islogin,usercontroller.loadlogin)
router.post('/login',midddlewares.checkBan,usercontroller.login)
router.get('/forgot/:email',usercontroller.forgot)
router.post('/verifyotpforg',usercontroller.otpverify)
router.post('/resetpassword',usercontroller.resetpassword)
router.post('/register',midddlewares.checkBan,usercontroller.register)
router.get('/otp',usercontroller.loadotp)
router.post('/otp',usercontroller.otpverify)
router.post('/resendotp',usercontroller.reotp)
router.get('/google/auth',usercontroller.googleauth)
router.get('/home',midddlewares.checkBan,usercontroller.loadhome)
router.get('/shop',midddlewares.checkBan,usercontroller.loadshop)
router.get('/shop/:name',midddlewares.checkBan,usercontroller.loadcategory)
router.get('/product/:name',midddlewares.checkBan,usercontroller.loadproductview)
router.get('/profile',midddlewares.checkBan,usercontroller.profileload)
router.get('/cart',midddlewares.checkBan,usercontroller.laodcart)
router.get('/cartremove/:productid', usercontroller.removeFromCart);
router.post('/editname',midddlewares.checkBan,usercontroller.changename)
router.post('/addtocart',midddlewares.checkBan,usercontroller.addtocart)
router.get('/logout',midddlewares.checkBan,usercontroller.logout)
router.put('/updatecart',usercontroller.updatecart)
router.post('/adresss',usercontroller.addadress)
router.post('/checkout',usercontroller.loadcheckout)
router.get('/orderdetials/:orderid',usercontroller.loadorderview)
router.post('/placeOrder',usercontroller.placeOrder)
router.delete('/delete-address/:id', usercontroller.deleteAddress);
router.put('/update-address',usercontroller.updateAddress)

module.exports = router;